## Hamoye Stage A Data Science Internship Quiz
Hi, I am Gaurav Jain, Data Science Intern at Hamoye AI.
Following is my Answers to Quiz Stage A on the fuel data set as described below.

Index:
<ul>
<li>Pre-eliminary Analysis</li>
<li>Quiz</li>

<span id="Pre-elim"></span>

In [1]:
#importing useful libraries like pandas, numpy

import pandas as pd
import numpy as np

#plotting and data visualization
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

C:\Users\JAIN\Anaconda3\lib\site-packages\statsmodels\tools\_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
url = "https://raw.githubusercontent.com/WalePhenomenon/climate_change/master/fuel_ferc1.csv"
#read the dataset and store it in 'df' variable as a Pandas DataFrame
df = pd.read_csv(url)

#describing the dataset for example its count, mean,std, etc
df.describe()

utility_id_ferc1   report_year  fuel_qty_burned  fuel_mmbtu_per_unit  \
count      29523.000000  29523.000000     2.952300e+04         29523.000000   
mean         118.601836   2005.806050     2.622119e+06             8.492111   
std           74.178353      7.025483     9.118004e+06            10.600220   
min            1.000000   1994.000000     1.000000e+00             0.000001   
25%           55.000000   2000.000000     1.381700e+04             1.024000   
50%          122.000000   2006.000000     2.533220e+05             5.762694   
75%          176.000000   2012.000000     1.424034e+06            17.006000   
max          514.000000   2018.000000     5.558942e+08           341.260000   

       fuel_cost_per_unit_burned  fuel_cost_per_unit_delivered  \
count               29523.000000                  2.952300e+04   
mean                  208.649031                  9.175704e+02   
std                  2854.490090                  6.877593e+04   
min                  -276.080000                 -8.749370e+02   
25%                     5.207000                  3.778500e+00   
50%                    26.000000                  1.737100e+01   
75%                    47.113000                  4.213700e+01   
max                139358.000000                  7.964521e+06   

       fuel_cost_per_mmbtu  
count         29523.000000  
mean             19.304354  
std            2091.540939  
min             -41.501000  
25%               1.940000  
50%               4.127000  
75%               7.745000  
max          359278.000000

In [3]:
print("\n Data Types of columns:\n")
print(df.dtypes) #gives datatypes of all the columns in DataFrame
print("\n Top 5 values of Data Set: \n")
df.head()


 Data Types of columns:

record_id                        object
utility_id_ferc1                  int64
report_year                       int64
plant_name_ferc1                 object
fuel_type_code_pudl              object
fuel_unit                        object
fuel_qty_burned                 float64
fuel_mmbtu_per_unit             float64
fuel_cost_per_unit_burned       float64
fuel_cost_per_unit_delivered    float64
fuel_cost_per_mmbtu             float64
dtype: object

 Top 5 values of Data Set: 



record_id  utility_id_ferc1  report_year  \
0   f1_fuel_1994_12_1_0_7                 1         1994   
1  f1_fuel_1994_12_1_0_10                 1         1994   
2   f1_fuel_1994_12_2_0_1                 2         1994   
3   f1_fuel_1994_12_2_0_7                 2         1994   
4  f1_fuel_1994_12_2_0_10                 2         1994   

       plant_name_ferc1 fuel_type_code_pudl fuel_unit  fuel_qty_burned  \
0              rockport                coal       ton        5377489.0   
1  rockport total plant                coal       ton       10486945.0   
2                gorgas                coal       ton        2978683.0   
3                 barry                coal       ton        3739484.0   
4             chickasaw                 gas       mcf          40533.0   

   fuel_mmbtu_per_unit  fuel_cost_per_unit_burned  \
0               16.590                      18.59   
1               16.592                      18.58   
2               24.130                      39.72   
3               23.950                      47.21   
4                1.000                       2.77   

   fuel_cost_per_unit_delivered  fuel_cost_per_mmbtu  
0                         18.53                1.121  
1                         18.53                1.120  
2                         38.12                1.650  
3                         45.99                1.970  
4                          2.77                2.570

<span id="Quiz"></span>
# **QUIZ**

----
<br>

#### Question 1

Extend list A to B

In [4]:
#Question 1
#Extend two list A and B

A=[1,2,3,4,5,6]
B=[13,21,34]
A.extend(B)
A_B=A

print(A)

[1, 2, 3, 4, 5, 6, 13, 21, 34]


------

<br>

#### Question 2 
Identity Matrix

In [5]:
#Question 2

identitym=np.identity(3)
print(identitym)

#Answer np.identity(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


----
<br>

#### Question 3

fuel type with lowest average fuel cost per unit burned

In [6]:
# Question 3
# fuel type with lowest average fuel cost per unit burned

df.groupby('fuel_type_code_pudl')['fuel_cost_per_unit_burned'].mean().sort_values()

fuel_type_code_pudl
gas          13.659397
other        18.253856
waste        19.518122
coal         67.421830
oil         168.877086
nuclear    4955.157002
Name: fuel_cost_per_unit_burned, dtype: float64

------------
<br>

#### Question 4

Standard Deviation and 75th Percentile in fuel_mmbtu_per_unit

In [7]:
# Question 4
#Standard Deviation and 75th percentile

#standard deviation
print("Standard Deviation is: ", round(df['fuel_mmbtu_per_unit'].std(),2))

#75th percentile
print("75th Percentile is: ", df['fuel_mmbtu_per_unit'].quantile(q=0.75).round(2))

Standard Deviation is:  10.6
75th Percentile is:  17.01


------

<br>

#### Question 5

Skewness and Kurtosis

In [8]:
#Question 5
#Skewness and Kurtosis

#skewness
print("Skewness is:",round(df['fuel_qty_burned'].skew(),2))

#Kurtosis
print("Kurtosis is: ",round(df['fuel_qty_burned'].kurtosis(),2))

Skewness is: 15.85
Kurtosis is:  651.37


-----
<br>

#### Question 6

Missing Values

In [9]:
#Question 6
#missing values

df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [10]:
percent_missing = sum(df.isnull().sum() * 100 / len(df))
print("Percentage of missing values: "+str(percent_missing)+" %")

Percentage of missing values: 0.6096941367747181 %


-------------------

#### Question 7
Missing Feature and Imputation technique

In [11]:
# Question 7
# Missing value feature and imputation technique 

# checking the column with null values

df.isnull().sum()

record_id                         0
utility_id_ferc1                  0
report_year                       0
plant_name_ferc1                  0
fuel_type_code_pudl               0
fuel_unit                       180
fuel_qty_burned                   0
fuel_mmbtu_per_unit               0
fuel_cost_per_unit_burned         0
fuel_cost_per_unit_delivered      0
fuel_cost_per_mmbtu               0
dtype: int64

In [12]:
# fuel_unit has missing values

# checking its data type

df.dtypes

record_id                        object
utility_id_ferc1                  int64
report_year                       int64
plant_name_ferc1                 object
fuel_type_code_pudl              object
fuel_unit                        object
fuel_qty_burned                 float64
fuel_mmbtu_per_unit             float64
fuel_cost_per_unit_burned       float64
fuel_cost_per_unit_delivered    float64
fuel_cost_per_mmbtu             float64
dtype: object

*Since fuel unit has dtype Object, So its a categorical variable
We will use mode imputation*

In [13]:
# checking the mode in fuel_unit
# for mode imputation

df.groupby('fuel_unit')['fuel_unit'].count()

# used group by and count functions

fuel_unit
bbl        7998
gal          84
gramsU      464
kgU         110
mcf       11354
mmbtu       180
mwdth        95
mwhth       100
ton        8958
Name: fuel_unit, dtype: int64

---------

#### Question 8

Second and Third lowest correlation


In [14]:
#Question 8
# Second and Third lowest correlation with fuel_cost_per_unit_burned

abs(df.corrwith(df['fuel_cost_per_unit_burned'])).sort_values()

fuel_cost_per_mmbtu             0.000437
fuel_mmbtu_per_unit             0.010034
fuel_cost_per_unit_delivered    0.011007
report_year                     0.013599
fuel_qty_burned                 0.018535
utility_id_ferc1                0.037863
fuel_cost_per_unit_burned       1.000000
dtype: float64

*Answer 8 is fuel_mmbtu_per_unit and fuel_cost_per_unit_delivered*

---------------
<br>

#### Question 9

Percentage Change in 1998 and 1994

In [15]:
# Question 9

yearly_cost = df.groupby(["report_year","fuel_type_code_pudl"])["fuel_cost_per_unit_burned"].sum()

year_1998,year_1994 = yearly_cost.loc[[1994,1998],"coal"]
percentage_change = ((year_1994-year_1998)/(year_1998))*100
percentage_change

-20.56765451826049

-----

<br>

#### Question 10

Highest Average fuel_cost_per_unit_delivered

In [16]:
#Question 10

df_year = df.groupby('report_year')['fuel_cost_per_unit_delivered'].mean().nlargest()
df_year

report_year
1997    11140.197239
1996     9196.705948
2000      985.362877
2009      652.694163
2018      499.269966
Name: fuel_cost_per_unit_delivered, dtype: float64

*Answer is 1997*

---------------------

### Thank You

-------------------------------------